version: 0.2

phases:
  install:
    commands:
      - echo "Starting install phase..."

  pre_build:
    commands:
      - echo "Starting install pre_build phase..."
      - echo "Starting pre-build phase..."
      - cd ~
      - git clone https://github.com/Maninder1220/WE3-C02-IaC.git
      - pwd
      - cd WE3-C02-IaC/Root
      - terraform init  # Downloading and configuring provider plugins
      - echo "Pre-build phase complete."

  build:
    commands:
      - echo "Starting build phase..."
      - terraform plan -out=tfplan  # Creating an execution plan for review
      - echo "Build phase complete."
      - pwd
      

  post_build:
    commands:
      - echo "Starting post-build phase..."
      - echo "Applying Terraform changes..."
      - terraform destroy -auto-approve tfplan  # Destroying infrastructure
      - echo "Terraform destroy complete."
      - echo "Post-build phase complete."
