version: 0.2

phases:
  install:
    commands:
      - echo "Starting install phase..."
      - apt install -y unzip wget  # Installing needed tools for Terraform
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_linux_amd64.zip
      - unzip terraform.zip -d /usr/local/bin/
      - terraform version  # Verifying Terraform installation
      - curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install.sh | bash
      - echo "Dependencies installed successfully."

  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - cd ../WE3-C02-IaC/Root
      - terraform init  # Downloading and configuring provider plugins
      - echo "Pre-build phase complete."

  build:
    commands:
      - echo "Starting build phase..."
      - terraform validate || { echo "Validation failed!"; exit 1; }
      - tflint || { echo "Linting failed!"; exit 1; }
      - terraform plan -out=tfplan  # Creating an execution plan for review
      - echo "Build phase complete."

  post_build:
    commands:
      - echo "Starting post-build phase..."
      - terraform apply -auto-approve tfplan  # Deploying infrastructure
      - echo "Terraform apply complete."
      - echo "Post-build phase complete."

artifacts:
  files:
    - tfplan  # Storing Terraform execution plan
  discard-paths: yes  # Optional: Removes folder paths from the artifact
